name: Versioning
#https://github.com/logankilpatrick/TODO-List-Updater/tree/master

on:
  push:
    branches:
      - main

concurrency:
  group: versioning-main
  cancel-in-progress: false

jobs:
  inject-version:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: version inject
        run: python ./.github/workflows/versioning.py
        env:
          COMMIT_HASH: ${{ github.sha }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          VERSIONING_MARKER: ${{ vars.VERSIONING_MARKER }}
          VERSIONING_PATH: ${{ vars.VERSIONING_PATH }}
      - name: commit append
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git add .
          git diff --cached --quiet && exit 0
          git commit -m "versioning"
          git push --force-with-lease origin HEAD:main